version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf5_apache
        ports:
          - 8011:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf5
        depends_on:
          - php

    php:
        build: .docker/php
        container_name: sf5_php
        volumes:
          - .:/home/wwwroot/sf5
